# Generated by Django 2.1.7 on 2019-04-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ao3_Fandom',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ao3_Story_Tracker',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('last_check_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffnet_username', models.CharField(max_length=255, null=True)),
                ('ao3_username', models.CharField(max_length=255, null=True)),
                ('local_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('upload_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fandom_id', models.IntegerField()),
                ('fandom_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ManyToManyField(to='story_search.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('word_count', models.IntegerField()),
                ('chapter_count', models.IntegerField()),
                ('publish_date', models.DateField()),
                ('update_date', models.DateField()),
                ('last_check_date', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField()),
                ('follow_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_search.Author')),
                ('characters', models.ManyToManyField(to='story_search.Character')),
                ('fandoms', models.ManyToManyField(to='story_search.Fandom')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='other_tags',
            field=models.ManyToManyField(to='story_search.Tag'),
        ),
        migrations.AddField(
            model_name='story',
            name='relationships',
            field=models.ManyToManyField(to='story_search.Relationship'),
        ),
        migrations.AddField(
            model_name='character',
            name='fandom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_search.Fandom'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_search.Story'),
        ),
    ]
