# Generated by Django 2.1.7 on 2019-04-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='fandom',
            name='fandom_id',
        ),
        migrations.RemoveField(
            model_name='fandom',
            name='fandom_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='character',
            name='same_as',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fandom',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='fandom',
            name='same_as',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='same_as',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ao3_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ffnet_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='fandom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story_search.Fandom'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
