# Generated by Django 2.1.7 on 2019-04-19 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_search', '0002_auto_20190418_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='publish_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name='story',
            name='update_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
