# Generated by Django 2.1.7 on 2019-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_search', '0004_auto_20190419_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(default='In Progress', max_length=16),
        ),
    ]
